# Netlify configuration file
[build]
  command = "npm run netlify-deploy"
  publish = "out"

[build.environment]
  NODE_VERSION = "18.17.0"
  NPM_VERSION = "9.6.7"
  NEXT_TELEMETRY_DISABLED = "1"
  BUILD_LOCALE = "ar"
  NETLIFY_NEXT_PLUGIN_SKIP = "false"

# Production context: all deploys from the Production branch set in your site's
# deploy settings will inherit these settings.
[context.production.environment]
  NODE_ENV = "production"
  NEXT_PUBLIC_SITE_URL = "https://esaudi.info"
  NEXT_PUBLIC_SITE_NAME = "يونيفورم"
  NEXT_PUBLIC_SITE_DESCRIPTION = "أفضل موقع متخصص في الأزياء الموحدة في المملكة العربية السعودية"
  NEXT_PUBLIC_DEFAULT_LOCALE = "ar"
  NEXT_PUBLIC_NETLIFY_ENV = "production"
  NEXT_PUBLIC_NETLIFY_SWR_CACHE_TTL = "86400"

# Deploy Preview context: all deploys resulting from a pull/merge request will
# inherit these settings.
[context.deploy-preview.environment]
  NODE_ENV = "development"
  NEXT_PUBLIC_SITE_URL = "https://deploy-preview-branch--uniform-blogs.netlify.app"

# Branch Deploy context: all deploys that are not from a pull/merge request or
# from the Production branch will inherit these settings.
[context.branch-deploy.environment]
  NODE_ENV = "development"
  NEXT_PUBLIC_SITE_URL = "https://branch-name--uniform-blogs.netlify.app"

# For Next.js
[[plugins]]
  package = "@netlify/plugin-nextjs"

# Optimize and compress images
[[plugins]]
  package = "netlify-plugin-submit-sitemap"

  [plugins.inputs]
  baseUrl = "https://esaudi.info"
    sitemapPath = "/sitemap.xml"
    providers = [
      "google",
      "bing"
    ]

# Redirecciones para URLs de blog con o sin barra final
[[redirects]]
  from = "/blog/flight-crew/:slug"
  to = "/blog/flight-crew/:slug/"
  status = 301
  force = true

# Redirecciones para otras categorías de blog
[[redirects]]
  from = "/blog/clinic-wear/:slug"
  to = "/blog/clinic-wear/:slug/"
  status = 301
  force = true

[[redirects]]
  from = "/blog/culinary-apparel/:slug"
  to = "/blog/culinary-apparel/:slug/"
  status = 301
  force = true

[[redirects]]
  from = "/blog/academic-attire/:slug"
  to = "/blog/academic-attire/:slug/"
  status = 301
  force = true

[[redirects]]
  from = "/blog/protective-services/:slug"
  to = "/blog/protective-services/:slug/"
  status = 301
  force = true

[[redirects]]
  from = "/blog/utility-services/:slug"
  to = "/blog/utility-services/:slug/"
  status = 301
  force = true

# Redirección para URLs de categorías de blog
[[redirects]]
  from = "/blog"
  to = "/blog/"
  status = 301
  force = true

# Manejo de parámetros de consulta de categoría
[[redirects]]
  from = "/blog/"
  query = {category = ":category"}
  to = "/blog/"
  status = 200
  force = false

# Redirecciones para páginas principales
[[redirects]]
  from = "/about"
  to = "/about/"
  status = 301
  force = true

[[redirects]]
  from = "/contact"
  to = "/contact/"
  status = 301
  force = true

[[redirects]]
  from = "/faq"
  to = "/faq/"
  status = 301
  force = true

[[redirects]]
  from = "/terms"
  to = "/terms/"
  status = 301
  force = true

[[redirects]]
  from = "/privacy"
  to = "/privacy/"
  status = 301
  force = true

[[redirects]]
  from = "/quote"
  to = "/quote/"
  status = 301
  force = true

# Fallback para categorías de blog
[[redirects]]
  from = "/blog/flight-crew/*"
  to = "/blog/flight-crew/index.html"
  status = 200
  force = false

[[redirects]]
  from = "/blog/clinic-wear/*"
  to = "/blog/clinic-wear/index.html"
  status = 200
  force = false

[[redirects]]
  from = "/blog/culinary-apparel/*"
  to = "/blog/culinary-apparel/index.html"
  status = 200
  force = false

# Redirects for specific flight articles (1-25)
[[redirects]]
  from = "/blog/flight-crew/flight-:number/"
  to = "/blog/flight-crew/flight-:number/index.html"
  status = 200
  force = false
  conditions = {Exists = {file = false}}

# Ensure category queries work
[[redirects]]
  from = "/blog/"
  query = {category = "clinic_wear"}
  to = "/blog/?category=clinic_wear"
  status = 200
  force = false

[[redirects]]
  from = "/blog/"
  query = {category = "culinary_apparel"}
  to = "/blog/?category=culinary_apparel"
  status = 200
  force = false

[[redirects]]
  from = "/blog/"
  query = {category = "flight_crew"}
  to = "/blog/?category=flight_crew"
  status = 200
  force = false

# Manejo de error 404 principal (debe ser la última regla)
[[redirects]]
  from = "/*"
  to = "/404.html"
  status = 404

# Set default headers for security
[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"
    Permissions-Policy = "camera=(), microphone=(), geolocation=()"

