[build]
  command = "npm run build"
  publish = ".next"

[build.environment]
  NODE_VERSION = "18.17.0"
  NPM_VERSION = "9.6.7"
  NEXT_TELEMETRY_DISABLED = "1"
  BUILD_LOCALE = "ar"
  NETLIFY_NEXT_PLUGIN_SKIP = "false"

# Production context: all deploys from the Production branch set in your site's
# deploy settings will inherit these settings.
[context.production.environment]
  NODE_ENV = "production"
  NEXT_PUBLIC_SITE_URL = "https://uniform-blogs.netlify.app"
  NEXT_PUBLIC_SITE_NAME = "يونيفورم"
  NEXT_PUBLIC_SITE_DESCRIPTION = "أفضل موقع متخصص في الأزياء الموحدة في المملكة العربية السعودية"
  NEXT_PUBLIC_DEFAULT_LOCALE = "ar"
  NEXT_PUBLIC_NETLIFY_ENV = "production"
  NEXT_PUBLIC_NETLIFY_SWR_CACHE_TTL = "86400"

# Deploy Preview context: all deploys resulting from a pull/merge request will
# inherit these settings.
[context.deploy-preview.environment]
  NODE_ENV = "development"
  NEXT_PUBLIC_SITE_URL = "https://deploy-preview-branch--uniform-blogs.netlify.app"

# Branch Deploy context: all deploys that are not from a pull/merge request or
# from the Production branch will inherit these settings.
[context.branch-deploy.environment]
  NODE_ENV = "development"
  NEXT_PUBLIC_SITE_URL = "https://branch-name--uniform-blogs.netlify.app"

# For Next.js Image Optimization
[[plugins]]
  package = "@netlify/plugin-nextjs"

[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Content-Security-Policy = "default-src 'self'; script-src 'self' 'unsafe-inline' 'unsafe-eval'; style-src 'self' 'unsafe-inline'; img-src 'self' data: blob:; font-src 'self' data:; connect-src 'self';" 